apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-admin-to-flask
  namespace: fayoz-final
spec:
  podSelector:
    matchLabels:
      app: flask-app
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: admin
  policyTypes:
  - Ingress
