apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-something
  namespace: fayoz-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeName: node2
      containers:
        - name: frontend
          image: nvrbckdown/something
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
