apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-exam
  namespace: fayoz-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-exam
  template:
    metadata:
      labels:
        app: final-exam
    spec:
      containers:
      - name: flask-container
        image: nvrbckdown/flask-app:final-exam
        env:
        - name: AUTHOR
          value: "YOUR_NAME"
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
